---------------------------------------Basic Analysis of the Data-------------------------------------

-- 1. The total revenue generated by the e-commerce platform
SELECT SUM(total_amount) AS Total_Revenue
FROM orders;
-- Output - Total_Revenue = 245670.50
-- Insight - This represents the total sales revenue generated from all customer orders.


-- 2. Total customers registered on the platform
SELECT COUNT(customer_id) AS Customer_Count
FROM customers;
-- Output - Customer_Count = 100
-- Insight - This shows the total number of customers currently registered.


-- 3. Total products available in the inventory
SELECT COUNT(product_id) AS AvailProducts
FROM inventory;
-- Output - AvailProducts = 50
-- Insight - This indicates the total number of products currently tracked in stock.